name: "Update Image and Push to Github Packages and Docker Hub"
on:
  schedule:
    - cron: "0 12 * * *" # Run every day at noon.
  workflow_dispatch:
jobs:
  rebuild-container:
    name: "Rebuild Container with the latest base image"
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: "Get Monero Release Tag"
        id: get_tag
        run: echo "::set-output name=tag::$(awk -F "=" '/MONERO_BRANCH=/ {print $2}' Dockerfile)"
      -
        name: Build and push to Docker Hub and Github Packages Docker Registry
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/sethsimmons/simple-monerod-docker/simple-monerod:latest
            ghcr.io/sethsimmons/simple-monerod-docker/simple-monerod:${{ steps.get_tag.outputs.tag }}
            sethsimmons/simple-monerod:latest
            sethsimmons/simple-monerod:${{ steps.get_tag.outputs.tag }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}