name: "Update Image and Push to Github Packages and Docker Hub when Dockerfile is changed"
# Run this workflow every time a new commit pushed to your repository
on:
  push:
    paths:
    - 'Dockerfile'
jobs:
  rebuild-container:
    name: "Rebuild Container"
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo.
      - name: "Checkout"
        uses: "actions/checkout@v2"

      # Get tag.
      - name: "Get Monero Release Tag"
        id: get_tag
        run: echo "::set-output name=tag::$(awk -F "=" '/MONERO_BRANCH=/ {print $2}' Dockerfile)"

      # Build and push the repo.
      - name: "Build and Push Docker images to Github Packages"
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/simple-monerod
          tags: latest, ${{ steps.get_tag.outputs.tag }}
          add_git_labels: true
      
      - name: "Build and push Docker images to Docker Hub"
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: sethsimmons/simple-monerod
          tags: latest, ${{ steps.get_tag.outputs.tag }}
          add_git_labels: true
